### ISSUE TITLE
Doesn't work for Pop!_OS 22.04 LTS x86_64

### ISSUE THREAD

**Issue by nsde** [albertosottile/darkdetect#19]
My `neofetch` info (excerpt):
**WM:** Mutter 
**WM Theme:** Pop 
**Theme:** Pop-dark [GTK2/3] 
**Icons:** Pop [GTK2/3]
**Terminal:** gnome-terminal

**Comment by nsde** [comment]
There is no error. But the package thinks I'm using a light mode even though my theme is dark.

**Comment by albertosottile** [comment]
Hi, thanks for reporting this. Your theme name ends in `-dark` so, the detection code should work. Could you run the following command
```
gsettings get org.gnome.desktop.interface gtk-theme
```

and report here the output? Thanks.

**Comment by nsde** [comment]
Sure.
<pre>(base) <font color="#26A269"><b>lix@on</b></font>:<font color="#12488B"><b>~</b></font>$ gsettings get org.gnome.desktop.interface gtk-theme
&apos;Pop-dark&apos;
(base) <font color="#26A269"><b>lix@on</b></font>:<font color="#12488B"><b>~</b></font>$ 
</pre>

**Comment by nsde** [comment]
I actually found out that `darkdetect` has some issues on Visual Studio Code:
![image](https://user-images.githubusercontent.com/67185896/167510512-148e012b-273d-4c67-a8bc-8db6521e1dd8.png)

**Comment by albertosottile** [comment]
Thanks for triaging this. Because we depend on the result of `gsettings get org.gnome.desktop.interface gtk-theme` for detecting the theme, I guess you would then have to report this issue upstream to either GNOME or VSCode. 

Hence, for the moment, I am closing this issue here.
