### ISSUE TITLE
Module produces ValueError on Windows 8.1

### ISSUE THREAD

**Issue by UDS-DavidM** [albertosottile/darkdetect#23]
The module incorrectly assumes that the output from platform.release() can be translated into int. This will cause an error on import in Windows 8.1.

```
Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\darkdetect\__init__.py", line 19, in <module>
    elif sys.platform == "win32" and int(platform.release()) >= 10:
ValueError: invalid literal for int() with base 10: '8.1'
```

Cheers.

**Comment by albertosottile** [comment]
This should have been fixed in #21, released in 0.6.0. Do you still experience this bug with the latest version of darkdetect?
