### ISSUE TITLE
ModuleNotFoundError: No module named 'darkdetect' in Python 3.8

### ISSUE THREAD

**Issue by DinRigtigeFar** [albertosottile/darkdetect#5]
I'm currently using python 3.8.7
I installed the package via:
`pip install darkdetect`
And it installs fine, but when I import it I get:
`ModuleNotFoundError: No module named 'darkdetect'`

I guess it has something to do with your setup file only containing python versions up til 3.7?
Could you please update it for newer versions of python?
Thanks in advance

**Comment by albertosottile** [comment]
I could, but classifiers have nothing to do with the package usability. I would double check if you are importing the package from the same version you installed it.

**Comment by albertosottile** [comment]
I could, but classifiers have nothing to do with the package usability. I would double check if you are importing the package from the same version you installed it.

**Comment by albertosottile** [comment]
Closing as no input has been provided in the past few months.
